// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuvbUG9b0QKlb_f9cUavhT2iUi2XmHr0Q',
    appId: '1:219622571466:web:00e79a532fe70858f96333',
    messagingSenderId: '219622571466',
    projectId: 'shopping-list-1d506',
    authDomain: 'shopping-list-1d506.firebaseapp.com',
    databaseURL: 'https://shopping-list-1d506.firebaseio.com',
    storageBucket: 'shopping-list-1d506.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi7kW_J85I6UM7EyukiL98g6bPt59Lq28',
    appId: '1:219622571466:android:2735bc6c6f49b554f96333',
    messagingSenderId: '219622571466',
    projectId: 'shopping-list-1d506',
    databaseURL: 'https://shopping-list-1d506.firebaseio.com',
    storageBucket: 'shopping-list-1d506.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGEgm1_zjbIWw3PapT4xWm8EG9RSFfjIg',
    appId: '1:219622571466:ios:e92ea18d5ede465cf96333',
    messagingSenderId: '219622571466',
    projectId: 'shopping-list-1d506',
    databaseURL: 'https://shopping-list-1d506.firebaseio.com',
    storageBucket: 'shopping-list-1d506.appspot.com',
    iosClientId: '219622571466-oqqv24prk351runpu83jt86eftjaks92.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterShoppinglist',
  );
}
